language: java
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "tsblock"
  - git config --local user.email "mpalts1234@hotmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $github_token
  file: "build/libs/proxyplugin-1.0-SNAPSHOT-all.jar"
  skip_cleanup: true
before_install:
  - chmod +x gradlew
script:
  - ./gradlew shadowJar
